Chore/implementing basic theme system
Ofadiman/pepe-commerce pull request #28
Opened 2021-03-22 17:02 UTC by EmilMalanczak

### I've implemented basic setup for theming system.

Mosts of the values will be changed I guess till we haven't prepared any theme yet.

final **`max`** import  inside app will look like this:

`import { spacing, animation, typography, colors, breakpoints } from '@design-system/styles'`

it also provides export for `GlobalStyles` component and `fontUrl` that is used across the app.

## Spacing
_Provides a function similar to Material-ui spacing util._ 

based on: [spacing-helper](https://github.com/binjospookie/spacing-helper) lightweight package with it's own typing

single value is equal 0.25rem which is 4px

example usages:
- `padding: spacing(2)` // 0.5rem
- `padding: spacing(1, 3)` // 0.25rem 0.75rem

## Colors
Includes all of the possible color variantions. 
They are just a reference to particular css variables implemented in `GlobalStyles`

- standard (primary, secondary etc.)
- monochrome (shapes between plain `white` and plain `black`) 
- status (status colors: positive, warning, negative)

## Breakpoints
Includes all of possible breakpoints across app.
They are just a reference to particular css variables implemented in `GlobalStyles`

## Typography
Includes all of constants connected with typography

- primary font
- font weights
- font sizes 

## Animation
Includes some useful keyframes that might be handy in future

2021-03-22 17:03 UTC, EmilMalanczak commented
A lot of changes comes from migration from CRA to create-next-app

2021-03-22 17:45 UTC, Ofadiman requested changes
Thanks for the PR. I left some comments that have to be addressed before we can merge.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/next-env.d.ts
> +/// <reference types="next" />
Do we really need this file? I don't think we are running NextJS app here, so it might not be necessary.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/package.json
> +    "next": "10.0.9",
I don't think we need `next` as a dependency in this package.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/package.json
> +    "spacing-helper": "^4.1.2",
`spacing-helper` package should be in `dependencies`. I took a look at it on npm and it looks like we are going to use it in production.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/styles/global.ts
> +  font-size: ${typography.size.s3}
Missing semicolon.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/styles/palette.ts
> +  // Palette
I don't think this comment adds any value here. We already know the context from variable name.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/styles/spacing.ts
> +import { createSpacing } from 'spacing-helper'
Nice package. I didn't know something like that exists :+1:

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/styles/spacing.ts
> +// single value is equal 0.25rem which is 4px
I would suggest removing this comment. It's kind of misleading because `1rem` does not always equal `16px`.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/stories/Button.stories.js
> +import React from 'react';
I'm not sure how those semicolons appeared here. We are using prettier config that should remove them. Please reformat the code.

2021-03-22 17:45 UTC, Ofadiman commented on packages/design-system/stories/Header.stories.js
> +import React from 'react';
Same case with semicolons as above.

2021-03-22 17:56 UTC, EmilMalanczak commented on packages/design-system/styles/spacing.ts
> +// single value is equal 0.25rem which is 4px
Yes and no 😄 `rem` unit changes mostly with resizing of window. We do not develop or watch websites _zoomed_ that is mostly used for accesibility reasons. Maybe add info like `in standard mode` ?

2021-03-22 17:58 UTC, EmilMalanczak commented on packages/design-system/package.json
> +    "spacing-helper": "^4.1.2",
according to this [link](https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies) `spacing-helper` will be available in production

2021-03-22 18:00 UTC, EmilMalanczak commented on packages/design-system/package.json
> +    "next": "10.0.9",
Yes, I want to make usage of `Link` and `Image` components which are a part of Next.js package

2021-03-22 18:01 UTC, EmilMalanczak commented on packages/design-system/next-env.d.ts
> +/// <reference types="next" />
I guess not in that case

2021-03-22 18:03 UTC, EmilMalanczak commented on packages/design-system/stories/Button.stories.js
> +import React from 'react';
They came from new storybook init - they will be formatted in near future with storybook setup.

2021-03-22 18:08 UTC, Ofadiman commented on packages/design-system/package.json
> +    "next": "10.0.9",
Right, I forgot about that :+1:

2021-03-22 18:14 UTC, Ofadiman commented on packages/design-system/package.json
> +    "spacing-helper": "^4.1.2",
I not sure about that. We will be building this package locally and installing it in other packages, so if the other package won't have `spacing-helper` library installed, it won't work.

2021-03-22 18:17 UTC, Ofadiman commented on packages/design-system/styles/spacing.ts
> +// single value is equal 0.25rem which is 4px
What about a case when someone sets `font-size: 62.5%;` on `html` tag? It's quite common approach and it's called [happy rems](https://dev.to/dominikilnicki/solve-rem-problem-with-the-happy-rems-approach-179).

2021-03-22 18:40 UTC, EmilMalanczak commented on packages/design-system/styles/spacing.ts
> +// single value is equal 0.25rem which is 4px
I doesn't make any change at this point I could say than `1rem does not always equal 10px`

2021-03-22 18:48 UTC, EmilMalanczak commented on packages/design-system/package.json
> +    "spacing-helper": "^4.1.2",
this [stack](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies) and [article ](https://code-trotter.com/web/dependencies-vs-devdependencies-vs-peerdependencies/#peerdependencies) explains how does that peerDependencies works. I see no problem till we keep installing it

2021-03-23 08:31 UTC, Ofadiman approved these changes

2021-03-23 19:40 UTC, merged